### ISSUE TITLE
Hide admin/toolbar setting shows up on /your-profile/ when using the Theme My Login plugin.

### ISSUE THREAD

**Issue by strangerstudios** [strangerstudios/hide-admin-bar-from-non-admins#1]
Hide admin/toolbar setting shows up on /your-profile/ when using the Theme My Login plugin.

**Comment by kimcoleman** [comment]
I tested with a non-admin role and the setting does not appear. 

It only appears for the "administrator" role, which is the only way the administrator using this plugin can control whether the admin bar appears or not for their account. I think this is useful and should not be removed.

![screen shot of administrator role themed profile](https://user-images.githubusercontent.com/5312875/38468176-7e5fe46c-3b10-11e8-8a9b-71756391f8f0.png)

![screen shot of non-admin role themed profile](https://user-images.githubusercontent.com/5312875/38468177-7e6c9b62-3b10-11e8-8c0d-a1a854695927.png)
